# 1. Convolution and Blurring 

In [1]:

import cv2  # importing the opencv module 
import numpy as np 

In [2]:
# Now reading the image that we have 
img=cv2.imread("obama.jpg")

In [3]:
print(img)  # Now we can see that by using opencv.imread function we can read the images

[[[ 33  16  13]
  [ 33  16  13]
  [ 32  16  13]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 32  18  14]
  [ 32  18  14]
  [ 32  18  14]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 31  20  16]
  [ 34  21  18]
  [ 35  22  20]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[156 154 181]
  [163 162 183]
  [169 168 185]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[155 155 180]
  [165 163 184]
  [170 169 186]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[155 155 180]
  [162 162 183]
  [170 169 187]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [5]:
# Now let us view the image by using imshow function 

cv2.imshow("img",img)    # This will display the image 
cv2.waitKey()            # This function will hold the screen/display like we use getch() in c/c++ language 
cv2.destroyAllWindows()  # This function is very important to use because this function will close/shut down all the display screen 
                         # we cam also say that cv2.destroyAllWindows will act like closing all opened files 

# the snapshot of the above output 
![img](/extras/snapshot1.jpg)

#  Now lets do Convolution on our image 

### A Convolution is a mathematical operation performed on two functions producing a third function which is typically a modified version of one of the original function 

output_image(modified image) = original_image x kernel_function

Where kernel_function is a matrix of our choice which have shape of any (2x3 or 5x5 or 7x7 and so on )

Now for performing convolution operation we have to change our 3d image to 2d image ie from colored image to black n white 




In [6]:
img=cv2.imread("obama.jpg",0)   # by putting 0 in imread function we can see black n white output of our colored image 

In [7]:
img.shape    # lets us see shape of img and we find that ys its actually 2d 

(337, 337)

In [9]:
cv2.imshow("img",img)
cv2.waitKey()
cv2.destroyAllWindows()

# This is the snapshot of above code's output 
![image.png](/extras/snapshot2.jpg)

In [10]:
# lets do convolution 
# Here the img is our original image and kernel is kernel function and the ouput image will be modified version of original image 

In [13]:

# Creating our 3 x 3 kernel/filter
kernel_3x3 = np.ones((3, 3), np.float32) / 9   # we divide out kernel matrix with 9 so that we can normalized our kernel ( scaled)

# We use the cv2.fitler2D to convolve the kernal with an image 
blurred = cv2.filter2D(img, -1, kernel_3x3)
cv2.imshow('3x3 Kernel Blurring', blurred)
cv2.waitKey(0)

# Creating our 7 x 7 kernel
kernel_7x7 = np.ones((7, 7), np.float32) / 49   # normalized by dividing the kernel with 49 so that there elements summed up to 1 

# We use the cv2.fitler2D to convolve the kernal with an image 
blurred2 = cv2.filter2D(img, -1, kernel_7x7)
cv2.imshow('7x7 Kernel Blurring', blurred2)
cv2.waitKey(0)

# Creating our 11 x 11 kernel
kernel_11x11=np.ones((11,11),np.float32)/121    # normalized by dividing kernel by 121 


# We use the cv2.fitler2D to convolve the kernal with an image 
blurred3= cv2.filter2D(img, -1, kernel_11x11)
cv2.imshow('11x11 Kernel Blurring', blurred3)
cv2.waitKey(0)

cv2.destroyAllWindows()

#  Snapshot of above cell's output
![image.png](/extras/snapshot3.jpg)

# Blurring by using cv2 functions and the convolution concept 

Now above we make our kernel/filter and then do convolution by using filter2d function. And there are various kernels that are designed for some specific purpose like blurring, sharpening, detecting edges and so on 

Now we use the inbuilt cv2 function that has built in kernel and will automatically perform convolution. Such functions are :
blur(), GaussianBlur(), medianBlur(), bilateralFilter(). Lets use all and see the result 

In [14]:

# Averaging done by convolving the image with a normalized box filter(ie kernel that designed for this bluring purpose)
# This takes the pixels under the box(kernel) and replaces the central element
# Box(kernel) size needs to odd and positive 
blur = cv2.blur(img, (3,3))
cv2.imshow('Averaging', blur)
cv2.waitKey(0)

# Instead of box filter, gaussian kernel
Gaussian = cv2.GaussianBlur(img, (7,7), 0)
cv2.imshow('Gaussian Blurring', Gaussian)
cv2.waitKey(0)

# Takes median of all the pixels under kernel area and central 
# element is replaced with this median value
median = cv2.medianBlur(img, 5)
cv2.imshow('Median Blurring', median)
cv2.waitKey(0)

# Bilateral is very effective in noise removal while keeping edges sharp
bilateral = cv2.bilateralFilter(img, 9, 75, 75)
cv2.imshow('Bilateral Blurring', bilateral)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Snapshot of above ouput 
![image.png](/extras/snapshot4.jpg)

# 2. Sharpening

### By altering our kernels we can implement sharpening, which has the effects of in strengthening or emphasizing edges in an image.

In [15]:

# Create our shapening kernel, we don't normalize since the 
# the values in the matrix sum to 1
kernel_sharpening = np.array([[-1,-1,-1], 
                              [-1,9,-1], 
                              [-1,-1,-1]])

# applying different kernels to the input image
sharpened = cv2.filter2D(img, -1, kernel_sharpening)

cv2.imshow('Image Sharpening', sharpened)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Snapshot of output 
![image.png](/extras/snapshot5.jpg)

In [17]:
# Thanks 
# for any query u can dm me on linkedin : https://www.linkedin.com/in/gurdeep-singh-bhatia-319441171/