Here we are taking the example of classifier and I have taken the Iris data from this link https://www.kaggle.com/jchen2186/machine-learning-with-iris-dataset/data

Import all the Dependencies

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix


Reading Data

In [3]:
df=pd.read_csv('Iris.csv')

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

Encoding our Labels

In [7]:
encode=LabelEncoder()
df['Species']=encode.fit_transform(df['Species'])

In [9]:
X=df.drop(['Id','Species'],axis=1)
y=df['Species']

Train Test Split

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

Train our Classifer

### Hyper Parameters:

**C** :- It is regularization parameter. The strength of the regularization is inversely proportional to C. Must be strictly positive. The penalty is a squared l2 penalty. default value of C is 1.

**kernel** :- {**linear**, **poly**, **rbf**, **sigmoid**, **precomputed**}, default=**rbf**
Specifies the kernel type to be used in the algorithm. It must be one of linear, poly, rbf, sigmoid, precomputed or a callable. If none is given, rbf will be used. 

**degree** :- Degree of the polynomial kernel function (poly). Ignored by all other kernels. degree default value is 3.

**gamma**:- {**scale**, **auto**}, default=**scale**
Kernel coefficient for rbf, poly and sigmoid.

if gamma=scale (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,

if auto, uses 1 / n_features.

In [14]:
svc=SVC()
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
accuracy=accuracy_score(y_pred,y_test)
report=classification_report(y_pred,y_test)
matrix=confusion_matrix(y_pred,y_test)

print('Accuracy:',accuracy)
print('------------------')
print('Confusion Matrix:\n',matrix)
print('------------------')
print('Classification Report:\n',report)

Accuracy: 1.0
------------------
Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
------------------
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Without using any hypertuning techniques we got the 100% accuracy.